# Generated by Django 3.2.5 on 2022-05-21 06:29

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0013_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='templateName',
            new_name='TemplateName',
        ),
        migrations.AddField(
            model_name='template',
            name='ColumnName',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='template',
            name='TemplateImage',
            field=models.FileField(default='', upload_to=pybo.models.file_name),
        ),
        migrations.AddField(
            model_name='template',
            name='User_Group',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='User_Range',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
