# Generated by Django 3.2.5 on 2022-05-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0014_auto_20220521_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='user_email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
