# Generated by Django 3.2.5 on 2022-05-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_template_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='user_email',
        ),
        migrations.AddField(
            model_name='template',
            name='email',
            field=models.CharField(default='', max_length=128, verbose_name='이메일'),
        ),
    ]
