# Generated by Django 3.2.5 on 2022-05-21 07:03

from django.db import migrations, models
import pybo.models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_auto_20220521_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='TemplateImage',
            field=models.FileField(upload_to=pybo.models.file_name, verbose_name='이미지'),
        ),
    ]
